---
abstract: 'A Pure Perl reimplementation of B Internals'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-Flat
provides:
  Acme::Flat:
    file: lib/Acme/Flat.pm
    version: '0.001001'
  Acme::Flat::AV:
    file: lib/Acme/Flat/AV.pm
    version: '0.001001'
  Acme::Flat::BINOP:
    file: lib/Acme/Flat/BINOP.pm
    version: '0.001001'
  Acme::Flat::COP:
    file: lib/Acme/Flat/COP.pm
    version: '0.001001'
  Acme::Flat::CV:
    file: lib/Acme/Flat/CV.pm
    version: '0.001001'
  Acme::Flat::FM:
    file: lib/Acme/Flat/FM.pm
    version: '0.001001'
  Acme::Flat::GV:
    file: lib/Acme/Flat/GV.pm
    version: '0.001001'
  Acme::Flat::HV:
    file: lib/Acme/Flat/HV.pm
    version: '0.001001'
  Acme::Flat::IO:
    file: lib/Acme/Flat/IO.pm
    version: '0.001001'
  Acme::Flat::IV:
    file: lib/Acme/Flat/IV.pm
    version: '0.001001'
  Acme::Flat::LISTOP:
    file: lib/Acme/Flat/LISTOP.pm
    version: '0.001001'
  Acme::Flat::LOOP:
    file: lib/Acme/Flat/LOOP.pm
    version: '0.001001'
  Acme::Flat::METHOP:
    file: lib/Acme/Flat/METHOP.pm
    version: '0.001001'
  Acme::Flat::NV:
    file: lib/Acme/Flat/NV.pm
    version: '0.001001'
  Acme::Flat::OP:
    file: lib/Acme/Flat/OP.pm
    version: '0.001001'
  Acme::Flat::PADOP:
    file: lib/Acme/Flat/PADOP.pm
    version: '0.001001'
  Acme::Flat::PMOP:
    file: lib/Acme/Flat/PMOP.pm
    version: '0.001001'
  Acme::Flat::PV:
    file: lib/Acme/Flat/PV.pm
    version: '0.001001'
  Acme::Flat::PVIV:
    file: lib/Acme/Flat/PVIV.pm
    version: '0.001001'
  Acme::Flat::PVLV:
    file: lib/Acme/Flat/PVLV.pm
    version: '0.001001'
  Acme::Flat::PVMG:
    file: lib/Acme/Flat/PVMG.pm
    version: '0.001001'
  Acme::Flat::PVNV:
    file: lib/Acme/Flat/PVNV.pm
    version: '0.001001'
  Acme::Flat::PVOP:
    file: lib/Acme/Flat/PVOP.pm
    version: '0.001001'
  Acme::Flat::REGEXP:
    file: lib/Acme/Flat/REGEXP.pm
    version: '0.001001'
  Acme::Flat::SV:
    file: lib/Acme/Flat/SV.pm
    version: '0.001001'
  Acme::Flat::SVOP:
    file: lib/Acme/Flat/SVOP.pm
    version: '0.001001'
  Acme::Flat::UNOP:
    file: lib/Acme/Flat/UNOP.pm
    version: '0.001001'
requires:
  Class::Tiny: '0'
  parent: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Acme-Flat/issues
  homepage: https://github.com/kentnl/Acme-Flat
  repository: https://github.com/kentnl/Acme-Flat.git
version: '0.001001'
